### ISSUE TITLE
Betiğin masaüstü ortamını silmesi görüntü sorunlarına ve çökmelere sebep verebilir

### ISSUE THREAD

**Issue by asandikci** [pardus-bireysel/pardus-bireysel#4]
### Olası çözüm yolları
1. betik çalıştırılmadan önce tty1 ekranina gecisin istenmesi
2. Otomatik olarak tty ekranına geçilmesi (implementasyonunun mümkün olup olmadığı ile ilgili araştırmaya ihtiyaç var)
3. Tüm xfce komponentleri silinince sadece çıktının gözüktüğü ve basit işlemlerin yapılabileceği bir ekran gösterilebilir (ileride, şimdilik gerek yok)

raporladığı için @mhmmdeminkl 'e teşekkürler

**Comment by misile00** [comment]
Alternatif çözüm:
1. KDE uygulamaları kurulacak ve gereksiz uygulamalar silinecek (kısacası bütün işlemler bitecek).
2. `systemctl restart lightdm` komutu ile LightDM servisi yeniden başlatılacak.

**Comment by asandikci** [comment]
#1 ile lightdm servisi yeniden başlatılmakta. Dolayısı ile en son sorun çözülmektedir. Lakin kod çalışırken ekran buga girebilir, kullanıcı sistemde sıkıntı olduğunu düşünebilir veya x display server çökebilir. Bu ve benzeri durumlar için bir fallback ekranı veya lighdtm ekranına atma işleminin erkenden yapılması göz önüne alınabilir.

İleride değerlendirmek adına açık tutuyorum

**Comment by asandikci** [comment]
TEST: KDE indirme/kurma süreci (#9) fazla uzun sürüyor ve bu sırada kullanıcı RAM'de tutulan xfce ortamında **stabil olmayan bir şekilde** kalıyor.

ÇÖZÜM:
XFCE-Sil > KDE-Yükle > LightDM-restart sırası:
KDE-Yükle > (XFCE-Sil >< LightDM-restart) ile değiştirilebilir

**Comment by asandikci** [comment]
Büyük ihtimal https://github.com/pardus-bireysel/pardus-bireysel/commit/f76c5d1c99b5730f953552f4e8eb2d6826826029 ile çözüme kavuşturuldu. Konuyu kapatıyorum.

İlgili bir eksiklikte geri açınız
